2023-01-18 10:30:26,756 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-01-18 10:30:26,760 INFO supervisord started with pid 7
2023-01-18 10:30:27,762 INFO spawned: 'nginx' with pid 10
2023-01-18 10:30:27,764 INFO spawned: 'app' with pid 11
2023-01-18 10:30:28,795 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-01-18 10:30:28,796 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Bottle v0.12.23 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

[CTRL] POST /setup
[Time: 18.01.23 10:30:30] [Level: info] id: 6ba7594c38d485cd
[Time: 18.01.23 10:30:30] [Level: info] coordinator: False
[Time: 18.01.23 10:30:30] [Level: info] clients: ['6ba7594c38d485cd']
[Time: 18.01.23 10:30:30] [Level: info] state: initial
127.0.0.1 - - [18/Jan/2023 10:30:30] "POST /api/setup HTTP/1.0" 200 0
[Time: 18.01.23 10:30:30] [Level: info] [State: initial]  Splits order:
[Time: 18.01.23 10:30:30] [Level: info] [State: initial] Split 0: /mnt/input/data/0
[Time: 18.01.23 10:30:30] [Level: info] [State: initial] Split 1: /mnt/input/data/1
[CTRL] GET /status
127.0.0.1 - - [18/Jan/2023 10:30:30] "GET /api/status HTTP/1.0" 200 149
[Time: 18.01.23 10:30:30] [Level: info] [State: initial] Getting sample shape from /mnt/input/data/0/train.npz dataset
[Time: 18.01.23 10:30:30] [Level: info] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 172, in guarded_run
    self.run()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 187, in run
    transition = self.current_state.run()
  File "/app/states.py", line 21, in run
    super().run()
  File "/app/utils/pytorch/states.py", line 32, in run
    dl = self.get_dataloader(self.load('input_files')['train'][0])
  File "/app/utils/pytorch/states.py", line 63, in get_dataloader
    dl_class = get_dataloader(self.config['train_config']['data_loader'])
  File "/app/utils/utils.py", line 45, in get_dataloader
    return get_custom_module(module=name, existing=SupportedLoaders, class_name='CustomDataLoader')
  File "/app/utils/utils.py", line 74, in get_custom_module
    spec.loader.exec_module(foo)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/input/ImageLoader.py'

[CTRL] GET /status
127.0.0.1 - - [18/Jan/2023 10:30:33] "GET /api/status HTTP/1.0" 200 141
